---
# tasks file for gentoo-apps
- name: Merge ebuilds
  portage:
    package: "{{ ebuilds }}"
    state: emerged
    update: yes
    verbose: yes
    newuse: yes
    loadavg: "{{ emerge_load_average }}"
    jobs: "{{ emerge_jobs_number }}"
- name: Add wk to docker group
  user:
    append: yes
    comment: Sviat
    createhome: yes
    group: wk
    groups:
    - docker
    name: wk
    shell: /bin/zsh
    state: present
- name: Enable and start docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  register: docker_start_srv
  failed_when: "docker_start_srv.failed and 'Service is in unknown state' not in docker_start_srv.msg"
- name: Enable and start LightDM service
  systemd:
    name: lxdm
    enabled: yes
    state: started
  register: lxdm_start_srv
  failed_when: "lxdm_start_srv.failed and 'Service is in unknown state' not in lxdm_start_srv.msg"
- name: Enable and start NetworkManager service
  systemd:
    name: NetworkManager
    enabled: yes
    state: started
  register: nm_start_srv
  failed_when: "nm_start_srv.failed and 'Service is in unknown state' not in nm_start_srv.msg"
- name: Configure network printer lookup in CUPS
  lineinfile:
    insertafter: "# Use BrowsePoll to poll a particular CUPS server"
    line: BrowsePoll cups.brq.redhat.com
    path: /etc/cups/cups-browsed.conf
    regexp: ^BrowsePoll\scups.brq.redhat.com$
    state: present
- name: Enable and start CUPS services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  register: cups_start_srv
  failed_when: "cups_start_srv.failed and 'Service is in unknown state' not in cups_start_srv.msg"
  with_items:
  - cups
  - cups-browsed
- name: Enable and start systemd services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  register: start_srv
  failed_when: "start_srv.failed and 'Service is in unknown state' not in start_srv.msg"
  with_items:
  - systemd-timesyncd
- name: Set up Kerberos
  template:
    src: krb5.conf.template
    dest: /etc/krb5.conf
- name: Set up sssd
  template:
    src: sssd.conf.template
    dest: /etc/sssd/sssd.conf
    mode: u=rw,g=,o=
- name: Enable and start sssd service
  systemd:
    name: sssd
    enabled: yes
    state: started
  register: start_srv
  failed_when: "start_srv.failed and 'Service is in unknown state' not in start_srv.msg"
