---
# tasks file for gentoo-apps
- name: Merge ebuilds
  portage:
    package: "{{ ebuilds }}"
    state: emerged
    update: yes
    verbose: yes
    newuse: yes
    loadavg: "{{ emerge_load_average }}"
    jobs: "{{ emerge_jobs_number }}"
- name: Ensure Vagga installed
  become_user: root
  shell: "curl -sSf https://files.zerogw.com/vagga/vagga-install{{ '-testing' if vagga_testing else '' }}.sh | sh"
  args:
    creates: /usr/bin/vagga
- name: Check kernel.unprivileged_userns_clone sysctl value
  become_user: root
  shell: sysctl kernel.unprivileged_userns_clone
  register: sysctl_cmd
  failed_when: >
    (sysctl_cmd.rc != 0 and
     'sysctl: cannot stat /proc/sys/kernel/unprivileged_userns_clone: No such file or directory'
     not in sysctl_cmd.stderr_lines) or
    (sysctl_cmd.rc == 0 and
     'kernel.unprivileged_userns_clone = 0'
     in sysctl_cmd.stdout_lines)
- name: Add wk to docker group
  user:
    append: yes
    comment: Sviat
    createhome: yes
    group: wk
    groups:
    - docker
    name: wk
    shell: /bin/zsh
    state: present
- name: Enable and start docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  register: docker_start_srv
  failed_when: "docker_start_srv.failed and 'Service is in unknown state' not in docker_start_srv.msg"
- name: Enable and start LightDM service
  systemd:
    name: lxdm
    enabled: yes
    state: started
  register: lxdm_start_srv
  failed_when: "lxdm_start_srv.failed and 'Service is in unknown state' not in lxdm_start_srv.msg"
- name: Enable and start NetworkManager service
  systemd:
    name: NetworkManager
    enabled: yes
    state: started
  register: nm_start_srv
  failed_when: "nm_start_srv.failed and 'Service is in unknown state' not in nm_start_srv.msg"
- name: Configure network printer lookup in CUPS
  lineinfile:
    insertafter: "# Use BrowsePoll to poll a particular CUPS server"
    line: BrowsePoll cups.brq.redhat.com
    path: /etc/cups/cups-browsed.conf
    regexp: ^BrowsePoll\scups.brq.redhat.com$
    state: present
- name: Configure remote network printer naming in CUPS
  lineinfile:
    insertafter: "# LocalQueueNamingRemoteCUPS RemoteName"
    line: LocalQueueNamingRemoteCUPS RemoteName
    path: /etc/cups/cups-browsed.conf
    regexp: ^LocalQueueNamingRemoteCUPS\sRemoteName$
    state: present
- name: Enable and start CUPS services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  register: cups_start_srv
  failed_when: "cups_start_srv.failed and 'Service is in unknown state' not in cups_start_srv.msg"
  with_items:
  - cups
  - cups-browsed
- name: Enable and start systemd services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  register: start_srv
  failed_when: "start_srv.failed and 'Service is in unknown state' not in start_srv.msg"
  with_items:
  - systemd-timesyncd
- name: Set up Kerberos
  template:
    src: krb5.conf.template
    dest: /etc/krb5.conf
- name: Set up sssd
  template:
    src: sssd.conf.template
    dest: /etc/sssd/sssd.conf
    mode: u=rw,g=,o=
- name: Enable and start sssd service
  systemd:
    name: sssd
    enabled: yes
    state: started
  register: start_srv
  failed_when: "start_srv.failed and 'Service is in unknown state' not in start_srv.msg"
