---
# tasks file for gentoo-apps
- name: Merge ebuilds
  portage:
    package: "{{ ebuilds }}"
    state: emerged
    update: yes
    verbose: yes
    newuse: yes
    loadavg: "{{ emerge_load_average }}"
    jobs: "{{ emerge_jobs_number }}"
  notify:
  - ensure-services-started
  - ensure-services-reloaded

- name: Ensure Vagga installed
  become_user: root
  shell: "curl -sSf https://files.zerogw.com/vagga/vagga-install{{ '-testing' if vagga_testing else '' }}.sh | sh"
  args:
    creates: /usr/bin/vagga
- name: Check kernel.unprivileged_userns_clone sysctl value
  become_user: root
  shell: sysctl kernel.unprivileged_userns_clone
  register: sysctl_cmd
  failed_when: >
    (sysctl_cmd.rc != 0 and
     'sysctl: cannot stat /proc/sys/kernel/unprivileged_userns_clone: No such file or directory'
     not in sysctl_cmd.stderr_lines) or
    (sysctl_cmd.rc == 0 and
     'kernel.unprivileged_userns_clone = 0'
     in sysctl_cmd.stdout_lines)
- name: Set up subuid/subgid
  lineinfile:
    create: yes
    line: wk:100000:65536
    path: /etc/sub{{ item }}id
    state: present
  with_items:
  - u
  - g

- name: Add wk to docker group
  user:
    append: yes
    comment: Sviat
    createhome: yes
    group: wk
    groups:
    - docker
    name: wk
    shell: /bin/zsh
    state: present

- name: Configure network printer lookup in CUPS
  lineinfile:
    insertafter: "# Use BrowsePoll to poll a particular CUPS server"
    line: BrowsePoll cups.brq.redhat.com
    path: /etc/cups/cups-browsed.conf
    regexp: ^BrowsePoll\scups.brq.redhat.com$
    state: present
  notify:
  - ensure-services-started
- name: Configure remote network printer naming in CUPS
  lineinfile:
    insertafter: "# LocalQueueNamingRemoteCUPS RemoteName"
    line: LocalQueueNamingRemoteCUPS RemoteName
    path: /etc/cups/cups-browsed.conf
    regexp: ^LocalQueueNamingRemoteCUPS\sRemoteName$
    state: present
  notify:
  - ensure-services-started

- name: Set up Kerberos
  template:
    src: krb5.conf.template
    dest: /etc/krb5.conf
  notify:
  - ensure-services-started
- name: Set up sssd
  template:
    src: sssd.conf.template
    dest: /etc/sssd/sssd.conf
    mode: u=rw,g=,o=
  notify:
  - ensure-services-started

- name: Create config dir structure for Google Chrome and Chromium
  file:
    dest: "{{ item.key }}"
    mode: "{{ item.value }}"
    owner: root
    group: root
    state: directory
    recurse: yes
  with_dict:
    /etc/chromium/policies/managed/: u+rwx,g=rx,o=rx
    /etc/chromium/policies/recommended/: u+rwx,g=rwx,o=rx
    /etc/opt/chrome/policies/managed/: u+rwx,g=rx,o=rx
    /etc/opt/chrome/policies/recommended/: u+rwx,g=rwx,o=rx
- name: Set up policies with whitelisted Kerberos servers for Google Chrome and Chromium
  copy:
    src: chrome-redhat-policy.json
    dest: "{{ item }}"
    mode: u+rw,g=r,o=r
    owner: root
    group: root
  with_items:
  - /etc/chromium/policies/managed/redhat.json
  - /etc/opt/chrome/policies/managed/redhat.json
