---
- name: Do gentoo world rebuild
  hosts: laptop
  become: yes
  tasks:
  - import_role:
      name: gentoo-services-ctl
  - name: Sync portage/layman trees and index ebuilds
    eix:
      action: sync
  - name: Rebuild the @world
    notify:
    - ensure-services-started
    - ensure-services-reloaded
    portage:
      name: "@world"
      state: emerged
      deep: yes
      update: yes
      verbose: yes
      newuse: yes
      loadavg: 4
      jobs: 9
  - name: Rebuild the @preserved-rebuild
    notify:
    - ensure-services-started
    - ensure-services-reloaded
    portage:
      name: "@preserved-rebuild"
      state: emerged
      verbose: yes
      loadavg: 4
      jobs: 9
