---
- name: Do gentoo world rebuild
  hosts: laptop
  become: yes
  tasks:
  - name: Rebuild the @world
    portage:
      name: "@world"
      state: emerged
      deep: yes
      update: yes
      verbose: yes
      newuse: yes
      loadavg: 4
      jobs: 9
  - name: Rebuild the @preserved-rebuild
    portage:
      name: "@preserved-rebuild"
      state: emerged
      verbose: yes
      loadavg: 4
      jobs: 9
