---
# shared handlers role. to use it, do:
# tasks:
# - import_role:
#     name: gentoo-services-ctl

# This must go first to preserve order
- name: Reload service definitions
  listen: reload-srv
  systemd:
    daemon_reload: yes

- name: Enable and start systemd services
  listen: ensure-services-started
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  register: start_srv
  failed_when: "start_srv.failed and 'Service is in unknown state' not in start_srv.msg"
  with_items: "{{ systemd_services }}"

- name: Restart systemd services
  listen: ensure-services-reloaded
  systemd:
    name: "{{ item }}"
    state: restarted
  register: start_srv
  failed_when: "start_srv.failed and 'Service is in unknown state' not in start_srv.msg"
  with_items: "{{ systemd_services }}"
