---
vagga_testing: no
git_options:
  user.email: wk@sydorenko.org.ua
  user.name: Sviatoslav Sydorenko
oh_my_zsh:
  editor: nvim
  plugins:
  - git
  - pyenv
  - ssh-agent
  - gpg-agent
code_workspace:
  source_dir: ~/src
  repos:
    - name: github
      fqdn: github.com
      slugs:
      - ansible/ansible
      - cherrypy/cheroot
      - cherrypy/cherrypy
      - cherrypy/magicbus
    - name: bitbucket
      fqdn: bitbucket.org
      slugs: []
