---
nvm_version: v0.33.8
node_versions:
  install:
  - &def_node_ver v9.8.0
  - 8
  default: *def_node_ver
git_options:
  commit.gpgsign: true
  gpg.program: gpg2
  user.email: wk@sydorenko.org.ua
  user.name: Sviatoslav Sydorenko
  user.signingkey: 9345E8FEA89CA455
oh_my_zsh:
  editor: nvim
  plugins:
  - git
  - pyenv
  - ssh-agent
  - gpg-agent
  - nvm
  custom_plugins:
    zsh-autosuggestions: git://github.com/zsh-users/zsh-autosuggestions.git
code_workspace:
  source_dir: ~/src
  repos:
    - name: github
      fqdn: github.com
      ssh_host_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      slugs:
      - aio-libs/aiohttp
      - aio-libs/aiohttp-devtools
      - aio-libs/multidict
      - amol-/dukpy
      - ansible/ansible
      - ansible/ansible-examples
      - ansible/foreman-test-container
      - benjaminp/six
      - candlepin/candlepin
      - cherrypy/cheroot
      - cherrypy/cherrypy
      - cherrypy/magicbus
      - dokku/dokku-mariadb
      - gentoo/gentoo
      - itkpi/beej-s-guide-to-network
      - jctanner/ansible-reproducers
      - kpi-web-guild/django-girls-blog-serhii73
      - pyenv/pyenv
      - PyGithub/PyGithub
      - pypa/auditwheel
      - pypa/get-pip
      - pypa/manylinux
      - pypa/pip
      - pypa/pipenv
      - pypa/pipfile
      - pypa/setuptools
      - pypa/setuptools_scm
      - pypa/ssl
      - pypa/twine
      - pypa/virtualenv
      - pypa/warehouse
      - pypa/wheel
      - python/core-workflow
      - python/cpython
      - python/miss-islington
      - travis-ci/dpl
      - webknjaz/check-in
      - webknjaz/mrgall-ansible
      - webknjaz/twitter-reporter
      - yaml/pyyaml
      forked_as:
        amol-/dukpy: webknjaz/dukpy
        ansible/ansible: webknjaz/ansible
        benjaminp/six: webknjaz/six
        gentoo/gentoo: webknjaz/gentoo
        jctanner/ansible-reproducers: webknjaz/ansible-reproducers
        pyenv/pyenv: webknjaz/pyenv
        PyGithub/PyGithub: webknjaz/PyGithub
        python/core-workflow: webknjaz/core-workflow
        travis-ci/dpl: webknjaz/dpl
        yaml/pyyaml: webknjaz/pyyaml
    - name: bitbucket
      fqdn: bitbucket.org
      ssh_host_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
      slugs: []
      forked_as: []
    - name: gitlab
      fqdn: gitlab.com
      ssh_host_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
      - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
      slugs:
      - remak-dva/components-api
      - remak-dva/phex-recutech-mcs
      - remak-dva/tbe-mcs
      forked_as: []
