---
vagga_testing: no
nvm_version: v0.33.8
node_versions:
  install:
  - &def_node_ver v9.8.0
  - 8
  default: *def_node_ver
git_options:
  user.email: wk@sydorenko.org.ua
  user.name: Sviatoslav Sydorenko
oh_my_zsh:
  editor: nvim
  plugins:
  - git
  - pyenv
  - ssh-agent
  - gpg-agent
  - nvm
code_workspace:
  source_dir: ~/src
  repos:
    - name: github
      fqdn: github.com
      slugs:
      - ansible/ansible
      - cherrypy/cheroot
      - cherrypy/cherrypy
      - cherrypy/magicbus
      - itkpi/beej-s-guide-to-network
      - pyenv/pyenv
    - name: bitbucket
      fqdn: bitbucket.org
      slugs: []
