---
- name: Set up user's git config
  git_config:
    name: "{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  with_dict: "{{ git_options }}"
- name: Get oh-my-zsh onto machine
  git:
    clone: yes
    dest: ~/.oh-my-zsh
    recursive: yes
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    update: yes
- name: Put oh-my-zsh enabled .zshrc config in place
  template:
    src: zshrc.zsh-template
    dest: ~/.zshrc
- name: Put Awesome WM enabled .xinitrc config in place
  template:
    src: xinitrc-template
    dest: ~/.xinitrc
- name: Create Awesome WM config dir within userspace
  file:
    dest: ~/.config/awesome
    state: directory
- name: Put Awesome WM resource script in place
  copy:
    src: awesome-rc.lua-template
    dest: ~/.config/awesome/rc.lua
- name: Ensure Vagga installed
  become_user: root
  shell: "curl -sSf https://files.zerogw.com/vagga/vagga-install{{ '-testing' if vagga_testing else '' }}.sh | sh"
  args:
    creates: /usr/bin/vagga
- name: Check kernel.unprivileged_userns_clone sysctl value
  become_user: root
  shell: sysctl kernel.unprivileged_userns_clone
  register: sysctl_cmd
  failed_when: >
    (sysctl_cmd.rc != 0 and
     'sysctl: cannot stat /proc/sys/kernel/unprivileged_userns_clone: No such file or directory'
     not in sysctl_cmd.stderr_lines) or
    (sysctl_cmd.rc == 0 and
     'kernel.unprivileged_userns_clone = 0'
     in sysctl_cmd.stdout_lines)
- name: Create experiments dir
  file:
    dest: "{{ code_workspace.source_dir }}/experiments"
    state: directory
- name: Sync github.com repos
  git:
    clone: yes
    dest: "{{ code_workspace.source_dir }}/github/{{ item }}"
    recursive: yes
    repo: "ssh://git@github.com/{{ item }}.git"
    update: yes
  with_items: "{{ code_workspace.repos.github }}"
  when: "'github' in code_workspace.repos"
- name: Sync bitbucket.org repos
  git:
    clone: yes
    dest: "{{ code_workspace.source_dir }}/bitbucket/{{ item }}"
    recursive: yes
    repo: "ssh://git@bitbucket.org/{{ item }}.git"
    update: yes
  with_items: "{{ code_workspace.repos.bitbucket }}"
  when: "'bitbucket' in code_workspace.repos"
- name: Sync gitlab.org repos
  git:
    clone: yes
    dest: "{{ code_workspace.source_dir }}/gitlab/{{ item }}"
    recursive: yes
    repo: "ssh://git@gitlab.org/{{ item }}.git"
    update: yes
  with_items: "{{ code_workspace.repos.gitlab }}"
  when: "'gitlab' in code_workspace.repos"
