---
vagga_testing: no
emerge_load_average: 4
emerge_jobs_number: 9
ebuilds:
- acpi
- alsa-utils
- app-emulation/docker
- arc-theme
- asciinema
- awesome
- bind-tools
- bbswitch
- cndrvcups-common-lb
- dpkg
- fira-code
- foomatic-db
- foomatic-db-engine
- foomatic-db-ppds
- git
- gentoo-sources
- google-chrome
- gutenprint
- htop
- i3lock
- intel-ocl-sdk
- irssi
- keybase
- layman
- libfprint
- libgnomecups
- links
#- lxc
- lxdm
- luajson
- luaposix
- luarocks
- luasocket
- materia-theme
- neovim
- networkmanager
- networkmanager-openvpn
- noto
- pam_krb5
- parcellite
- pavucontrol
- pcsc-lite
- pulseaudio
- qrencode
- rust-bin
- sic
- sssd
- st
- telnet-bsd
- tmux
- twemoji-color-font
- unicode-emoji
- wmname
- xautolock
- xorg-x11
